### ISSUE TITLE
Add documentation on how to autowire handlers 

### ISSUE THREAD

**Issue by cmodijk** [SimpleBus/docs#45]
```
services:
    Infrastructure\CommandBus\Handler\:
        resource: '../../src/Infrastructure/CommandBus/Handler'
        public: true
        tags:
            - 'command_handler'
```

```
    Infrastructure\EventBus\Listener\:
        resource: '../../src/Infrastructure/EventBus/Listener'
        public: true
        tags:
            - 'event_subscriber'
```

@ruudk Do you have time for this?
